# Generated by Django 4.0 on 2022-07-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='タグ名')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks', models.CharField(max_length=40)),
                ('text', models.TextField(blank=True, null=True)),
                ('complete_time', models.TimeField()),
                ('tags', models.ManyToManyField(to='nodolist.Tag', verbose_name='Tagモデルのname')),
            ],
        ),
    ]
