# Generated by Django 4.0 on 2022-07-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='完了フラグ'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, verbose_name='tag_name'),
        ),
    ]
