# Generated by Django 4.0 on 2022-07-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodolist', '0002_post_is_done_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='complete_time',
            # field=models.IntegerField(),
        ),
    ]
