# Generated by Django 4.0 on 2022-07-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodolist', '0003_alter_post_complete_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='nodolist.Tag', verbose_name='Tagモデルのname'),
        ),
    ]
